[package]
name = "onboard"
version = "0.1.0"
edition = "2018"
authors = ["0L contributors"]
description = "0L onboarding wizard"
repository = "https://github.com/OLSF/libra"
homepage = "https://github.com/olsf/"

[dependencies]
wait-timeout = "0.2.0"
gumdrop = "0.7"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
serde_json = "1"
libra-wallet = { path = "../../testsuite/cli/libra-wallet", version = "0.1.0" }
libra-types = { path = "../../types/", version = "0.1.0" }
rustyline = "6.2.0"
anyhow = "1.0.31"
toml = "0.5.6"
reqwest = { version = "0.10.6", features = ["blocking", "json"], default_features = false }
libra-global-constants = { path = "../../config/global-constants", version = "0.1.0"}
dirs = "2.0.2"
transaction-builder = { path = "../../language/transaction-builder", version = "0.1.0"}
libra-network-address = { path = "../../network/network-address", version = "0.1.0" }
libra-genesis-tool = { path = "../../config/management/genesis", version = "0.1.0" }
keygen = { path = "../keygen/", version = "0.1.0" }
ol-cli = { path = "../cli"}
txs = { path = "../txs"}
ol-types = { path = "../../ol/types"}
miner = { path = "../miner" }

[dependencies.abscissa_core]
version = "0.5.2"

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
once_cell = "1.2"
criterion = "0.3"
