[workspace]
miner_home = "."
node_home = "."

[profile]
auth_key = "2cdf9f42a6667e758907327fbdbb8f8b664d73699392e694561c7e116752b357"
account = "664D73699392E694561C7E116752B357"
ip = "0.0.0.0"
statement = "Protests rage across the nation"

[chain_info]
chain_id = "experimental"
block_dir = "blocks"
node = "http://localhost:8080"
