[workspace]
miner_home = "."
node_home = "."

[profile]
auth_key = "cb4d398c224396785c1fc219fbae0c16f5c41fddb0aff1bb28e5845634fd6e5d"
account = "B5B333AABBF92E78524E2129B722EACA"
ip = "0.0.0.0"
statement = "Protests rage across the nation"

[chain_info]
chain_id = "experimental"
block_dir = "blocks"
node = "http://localhost:45625"
