[workspace]
miner_home = "."
node_home = "."

[profile]
auth_key = "2cdf9f42a6667e758907327fbdbb8f8b664d73699392e694561c7e116752b357"
account = "286CB7B8090141E031EBF2B7F2C427AA"
ip = "0.0.0.0"
statement = "Protests rage across the nation"

[chain_info]
chain_id = "experimental"
block_dir = "blocks"
node = "http://localhost:46377"
