name: Chain Upgrade

on:
  push:
    branches: [ main, 'release**', ci ]
  pull_request:
    branches: [ main, 'v**', 'release**' ]
    
jobs:
  functional:
    name: Stdlib Upgrade
    runs-on: self-hosted
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.46.0
            override: true
            components: rustfmt, clippy
      - name: Install deps
        run: sudo apt-get install -y lld
      - name: Check branch
        run: echo "${{ steps.branch-name.outputs.current_branch }}"
      - name: File permissions
        run: sudo chmod -R 777 language/stdlib/ 
      - name: Swarm upgrade test
        run: BRANCH_NAME=${{ steps.branch-name.outputs.current_branch }} RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/util/test-upgrade.mk test
  